### ISSUE TITLE
[BE] Process postcoordination spec events for GET entity axis status.

### ISSUE THREAD

**Issue by alexsilaghi** [who-icatx/webprotege-postcoordination-service#14]
Given an entityIRI + projectId we need to process the postcoordination specification events to create the current state. The info will be used on the table for the display. The response should look something like this : 

```
whoficEntityIri: http://id.who.int/icd/entity/1435254666,

	postcoordinationSpecifications: [
	{
		linearizationView: http://id.who.int/icd/release/11/mms,
		{
          requiredAxes: [
            http://id.who.int/icd/schema/hasCausingCondition
          ],
          allowedAxes: [
            http://id.who.int/icd/schema/hasSeverity,
            http://id.who.int/icd/schema/associatedWith
          ]
        },
```

When applying the events, we need to check if the postcoordination axis exists in other arrays so we remove it . IN this way we have for a linearizationView a postCoordinationAxis into a single state.

**Comment by soimugeoWB** [comment]
@alexsilaghi i think this is done right?
