### ISSUE TITLE
[FE] Enable readonly / editable mode for the postcoordination

### ISSUE THREAD

**Issue by alexsilaghi** [who-icatx/webprotege-postcoordination-service#15]
We need to implement two states for the PostCoordination view , ReadOnly and editable

the state "readOnly" should be on the entire view (scale values + table)

Both table and scale value cards should have an internal state "readOnly" and have a mutator that can change the state.

when in ReadOnly mode for the table , the checks are disabled and can't be edited.
when in ReadOnly mode for the scale values cards , the buttons are not shown.
when In ReadOnly mode the modal is not shown in the cards.

If "Cancel" is hit, we fetch the data from the server and refresh the view.

**Comment by soimugeoWB** [comment]
i'll work on this for the scale value cards also.
