### ISSUE TITLE
[FE] Display existing postcoordination view 

### ISSUE THREAD

**Issue by alexsilaghi** [who-icatx/webprotege-postcoordination-service#4]
Based on the presenter developed in https://github.com/who-icatx/webprotege-postcoordination-service/issues/5 we need to fetch the configuration of an existing entity and populate the table with the values received from BE

TODO discuss how we will provide to the backend request the entity Type so we can fetch the correct table configuration

@tudorache said to use by default ICD

**Comment by soimugeoWB** [comment]
i think this is only for the configuration of the table. can we close this @alexsilaghi ?
