### ISSUE TITLE
[FE] Integrate with filtered tree display (linearization parent, postcoordination scales values, logical definition values).

### ISSUE THREAD

**Issue by alexsilaghi** [who-icatx/webprotege-postcoordination-service#42]
We need to replace the current solution with the newly developed filtered tree.

- Linearization parent . Here we will fetch only the direct ancestors.
- postcoordination scales values - here we fetch the info from the axis to generic scales table in the backend as root, and we select a single value.
- Logical definition values - here add all set scales as roots , if no scale is set then we fetch the axis to generic scales table and use the root from there.

Depends on issue [icat issue 53](https://github.com/who-icatx/icatx-project/issues/53)

**Comment by soimugeoWB** [comment]
I think that first bullet point is no longer valid. If we have only the direct parents then we don't need a try to display it, just a dropdown which has already been implemented for the linearization view.
